name: Compilar v39

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Descargar codigo
      uses: actions/checkout@v4

    - name: Instalar Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Compilar ejecutable optimizado
      run: cargo build --release

    - name: Guardar ejecutable como artefacto
      uses: actions/upload-artifact@v4
      with:
        name: il2cpp-dumper-v39-windows
        path: target/release/il2cpp_dumper.exe
